# fetch Cisco ASA configuration using asa_facts module
#
---
- cisco.asa.asa_facts:
    gather_subset: config

- set_fact:
    ansible_net_config: "{{ lookup('template','_asav_config_cleanup.j2') }}"
